/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        navy: {
          DEFAULT: '#1B3A5C',
          50: '#EEF2F7',
          100: '#D6DFEB',
          200: '#AEC1D6',
          300: '#7E9BBC',
          400: '#4E739F',
          500: '#2E5F8A',
          600: '#1B3A5C',
          700: '#142C46',
          800: '#0F2238',
          900: '#091628',
        },
        gold: {
          DEFAULT: '#D4A853',
          50: '#FBF6EA',
          100: '#F6EAC8',
          200: '#ECD491',
          300: '#E1BD5C',
          400: '#D4A853',
          500: '#B98A35',
          600: '#8E6926',
          700: '#65491A',
        },
        surface: {
          DEFAULT: '#F8F7F4',
          card: '#FFFFFF',
          muted: '#F1EFEA',
        },
        ink: {
          DEFAULT: '#1A1A2E',
          secondary: '#5A6070',
          muted: '#8B91A1',
        },
        line: '#E2DDD6',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        success: {
          DEFAULT: '#2D7A4F',
          foreground: '#FFFFFF',
          soft: '#E6F2EC',
        },
        warning: {
          DEFAULT: '#C17B2A',
          foreground: '#FFFFFF',
          soft: '#FAEFD9',
        },
        danger: {
          DEFAULT: '#B03A2E',
          foreground: '#FFFFFF',
          soft: '#F8E1DE',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: '#1B3A5C',
          2: '#D4A853',
          3: '#2D7A4F',
          4: '#C17B2A',
          5: '#5A6070',
        },
      },
      boxShadow: {
        soft: '0 1px 2px rgba(15,34,56,0.06), 0 1px 3px rgba(15,34,56,0.04)',
        card: '0 4px 14px rgba(15,34,56,0.06), 0 1px 3px rgba(15,34,56,0.04)',
        modal: '0 24px 48px -12px rgba(15,34,56,0.18)',
        gold: '0 8px 24px -8px rgba(212,168,83,0.45)',
        glass: '0 8px 32px rgba(15,34,56,0.08), inset 0 1px 1px rgba(255,255,255,0.80)',
        'glass-dark': '0 8px 32px rgba(0,0,0,0.35), inset 0 1px 1px rgba(255,255,255,0.06)',
        'glass-gold': '0 8px 24px rgba(212,168,83,0.25), inset 0 1px 1px rgba(255,255,255,0.40)',
        'sidebar': '4px 0 30px rgba(0,0,0,0.40)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { '0%': { opacity: '0', transform: 'translateY(6px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(18px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { '0%': { opacity: '0', transform: 'translateX(20px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'pulse-soft': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        'float': { '0%, 100%': { transform: 'translateY(0px) scale(1)' }, '50%': { transform: 'translateY(-14px) scale(1.02)' } },
        'glow-pulse': { '0%, 100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
        'morph': {
          '0%':   { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
          '25%':  { borderRadius: '40% 60% 55% 45% / 45% 55% 45% 55%' },
          '50%':  { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
          '75%':  { borderRadius: '55% 45% 40% 60% / 40% 70% 55% 45%' },
          '100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
        },
        'liquid-drift': {
          '0%':   { transform: 'translate(0px, 0px) scale(1)' },
          '33%':  { transform: 'translate(14px, -10px) scale(1.07)' },
          '66%':  { transform: 'translate(-10px, 12px) scale(0.94)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        'shimmer': {
          '0%':   { transform: 'translateX(-100%) skewX(-15deg)' },
          '100%': { transform: 'translateX(240%) skewX(-15deg)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.35s ease-out',
        'fade-up': 'fade-up 0.5s cubic-bezier(0.16,1,0.3,1)',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'float': 'float 7s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'morph': 'morph 9s ease-in-out infinite',
        'liquid-drift': 'liquid-drift 12s ease-in-out infinite',
        'shimmer': 'shimmer 2.4s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
